################################################################################
#
# plot_nmds.R
#
# Here we take in the *.nmds.axes file from the mouse stability analysis and
# plot it in R as we did in Figure 4 of Kozich et al.
#
# Dependencies:   2-D axes file generated by the nmds command in mothur
# Produces:       results/figures/nmds_figure.png
#
################################################################################
plot_nmds <- function (axes_file){
  axes <- read.table(file=axes_file, header=T, row.names=1)
#  day <- as.numeric(gsub(".*D(\\d*)$", "\\1", rownames(axes)))
  day <- as.numeric(gsub(".*D(\\d*)_.*$", "\\1", rownames(axes)))
  early <- day <= 10
  late <- day >= 140 & day <= 150
  plot_axes <- axes[early | late, ]
  plot_day <- day[early | late]
  plot_early <- early[early | late]
  plot_late <- late[early | late]
  pch <- vector()
  pch[plot_early] <- 21
  pch[plot_late] <- 19
  output_file_name <- "results/figures/nmds_figure.png"
  png(file=output_file_name)
    plot(plot_axes$axis2~plot_axes$axis1, pch=pch, xlab="PCoA Axis 1",
                    ylab="PCoA Axis 2")
    legend(x=max(plot_axes$axis1)-0.125, y=min(plot_axes$axis2)+0.125,
                    legend=c("Early", "Late"), pch=c(21,19))
  dev.off()
}
